### ISSUE TITLE
get-ready.md 번역

### ISSUE THREAD

**Issue by serithemage** [alexa-krug/workshop-in-skill-purchasing#3]

**Comment by Danpatpang** [comment]
번역 작업은 처음인데 제가 해봐도 괜찮을까요?

**Comment by serithemage** [comment]
넵! 물론입니다! 잘 부탁드립니다!
처음 하시는 거라면 번역 가이드를 우선 읽어주세요.
https://github.com/awskrug/awskrug-rule-book/wiki/Hands-on-lab-translation-guide

**Comment by serithemage** [comment]
> 번역 작업은 처음인데 제가 해봐도 괜찮을까요?

넵! 물론입니다! 잘 부탁드립니다!
처음 하시는 거라면 번역 가이드를 우선 읽어주세요.
https://github.com/awskrug/awskrug-rule-book/wiki/Hands-on-lab-translation-guide
